### ISSUE TITLE
Any chances of you adding other packages to this?

### ISSUE THREAD

**Issue by accedic** [silv3rr/docker-glftpd#2]
Was just wondering if there was any chances of you adding packages like euro pre system and various other addons?
Thanks in advance.

**Comment by silv3rr** [comment]
Currently you'd have to add your own docker args to bind mount script and conf into /glftpd dir in container.
Another way to do it would be to just mount your glftpd/bin on top i guess.

Next version adds custom entrypoint scripts and bind mount, including an example where you put scripts in local ./custom/scripts and they get copied to /glftpd/bin.

It also adds full user mgmt via webui btw..

![image](https://github.com/silv3rr/docker-glftpd/assets/20193226/6f6ba1e2-b6e4-435e-a84d-31e5ec7928fc)

**Comment by accedic** [comment]
Damn, next version looks sweet. Thanks for the input. I will give that a try.

**Comment by accedic** [comment]
@silv3rr  This should defininitly get a helmchart for truenas scale. I actually modified it a bit and got it up and running on TrueNas Scale. I'm working on another project in parallel. However if you are open to collaboration on this. Hit me up we could discuss a road map and work on this together.

**Comment by silv3rr** [comment]
> @silv3rr This should defininitly get a helmchart for truenas scale. I actually modified it a bit and got it up and running on TrueNas Scale. I'm working on another project in parallel. However if you are open to collaboration on this. Hit me up we could discuss a road map and work on this together.

Currently i'm trying to finish the webui, sometime this year :) TrueNas Scale looks cool but tbh not really interested. Feel free to use anything from the repo as you please.

**Comment by jotosmurf** [comment]
@accedic 
> This should defininitly get a helmchart for truenas scale. I actually modified it a bit and got it up and running on TrueNas Scale..

Would you mind sharing what you changed? I think it's a great idea to have this as a TrueNAS SCALE app. 
If you're up for it, we could even start a fork and keep it up to date based on silv3rr's awesome work :-)
